# Generated by Django 5.0.6 on 2024-06-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='traveler',
            field=models.ManyToManyField(related_name='traveler', to='exam.users'),
        ),
    ]
